config/routes.rb
Rails.application.routes.draw do
  get 'posts/index'
  get 'posts/dashboard'
  get 'posts/create'
  
  post '/posts/create', to: 'posts#create', as:'posts'
  
  root 'posts#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  #http_basic_authenticate_with name: "desafiovamoscontodo", password: "XAHTJEAS23123%23", only: :dashboard

    def index
      @posts = Post.all.order(created_at: :desc)
    end

    def dashboard
      @post = Post.new

    end

  def create
      @post = Post.create(post_params)
  end

    private
      def post_params
        params.require(:post).permit(:title, :image_url, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-dark bg-warning" >
    <div class="container">
        <span class="navbar-brand mb-0 h1"><%= link_to 'Inicio', posts_index_path %></span>
        <span class="navbar-brand mb-0 h1"><%= link_to 'Administradores', posts_dashboard_path %></span>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

  </head>

  <body>
      <%= render partial:'/layouts/navbar' %>
    <div class="container">
      
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/create.html.erb
<h2 class="mx-auto" style="width: 500px;"> Nuevo Artículo </h2>

<form class="mx-auto" style="width: 500px;" id="create_posts" method="post" action="/posts/create">

    <%= form_with scope: :post, url: posts_path, local: true do |f| %>
    
    <p>
        <%= f.label "Título" %><br>
        <%= f.text_field :title %>
    </p>

    <p>
        <%= f.label "URL de la imagen"%><br>
        <%= f.text_field :image_url %>
    </p>

    <p>
        <%= f.label "Contenido"%><br>
        <%= f.text_area :content %>
    </p>

    <p>
        <%= f.submit "Guardar" %>
    </p>
    <% end %>
</form>

app/views/posts/dashboard.html.erb
<h2 class="mx-auto" style="width: 500px;"> Nuevo Artículo </h2>

    <form class="mx-auto" style="width: 500px;" id="create_posts" method="post" action="/posts/create">

        <%= form_with scope: :post, url: posts_path, local: true do |f| %>
        
        <p>
            <%= f.label "Título" %><br>
            <%= f.text_field :title %>
        </p>

        <p>
            <%= f.label "URL de la imagen"%><br>
            <%= f.text_field :image_url %>
        </p>

        <p>
            <%= f.label "Contenido"%><br>
            <%= f.text_area :content %>
        </p>

        <p>
            <%= f.submit "Guardar" %>
        </p>
        <% end %>
    </form>

app/views/posts/index.html.erb
<h1>Indice de Posts</h1>

<table class="table">
        <tr>
            <th> Título </th>
            <th> Fecha </th>
            <th> Link a imagen </th>
            <th> Contenido </th>
        </tr>

    <% @posts.each do |post|%>
        <tr>
            <td><%= post.title %></td>
            <td><%= post.created_at.strftime("%d %b. %Y") %></td>
            <td><%= link_to post.image_url %></td>
            <td><%= post.content %></td>
        </tr>
    <%end%>

</table>